<?php

namespace backend\controllers;

use backend\search\BuyurtmaSearch;
use backend\search\OnlineMurojatlarSearch;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
                'denyCallback' => function ($r, $a) {
                    Yii::$app->user->logout();
                    Yii::$app->session->setFlash("danger", "Sizda bu tizimga kirish ruhsati yo'q");
                    Yii::$app->user->loginRequired();
                }
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->layout = "clean";
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->layout="app";
        $OnlinesearchModel = new OnlineMurojatlarSearch();
        $OnlinedataProvider = $OnlinesearchModel->search(Yii::$app->request->queryParams);
        $BuyurtmasearchModel = new BuyurtmaSearch();
        $dataProvider = $BuyurtmasearchModel->search(Yii::$app->request->queryParams);
        return $this->render('index',
            [
                'OnlinesearchModel' => $OnlinesearchModel,
                'searchModel' => $BuyurtmasearchModel,
                'OnlinedataProvider' => $OnlinedataProvider,
                'dataProvider' => $dataProvider,
            ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout = "clean";
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}
